### PR TITLE
Copy all the source code from serving-operator repo to new repo

### PR DESCRIPTION
**Pull request by houshengbo**
## Proposed Changes

* This PR is based on the commit d0e771a0a4adb9893b9e7af9c9eb866f9dd937df of serving-operator repo.
* We replace `/serving-operator/` with `/operator/` to fit the new repo.
* We can issue the command `ko apply -f config` to launch the operator of serving.

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by chaodaiG** [comment]
if !isAuthor && !skipCollaborators && !isCollaborator {
		resp := "changing LGTM is restricted to collaborators"
		log.Infof("Reply to /lgtm request with comment: \"%s\"", resp)
		return gc.CreateComment(org, repoName, number, plugins.FormatResponseRaw(body, htmlURL, author, resp))
	}

**Comment by chaodaiG** [comment]
Guess we need to join knative-sandbox org gaining power

**Comment by k4leung4** [comment]
@googlebot I consent.

**Comment by k4leung4** [comment]
@googlebot I consent.

**Comment by Cynocracy** [comment]
aw, I'm late to the party :)

**Pull request merged**
